# Site settings
title: Alejandro H. Pineda
email: ale.hpineda@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Mi curriculum vitae en linea hospedado en Github pages utilizando Jekyll en ingles y español
baseurl: "/cv" # the subpath of your site, e.g. /blog/
url: "http://deathscytheh.github.io" # the base hostname & protocol for your site
twitter_username: deathscytheh
github_username:  deathscytheh
facebook_username: deathscythe
linkedin_username: alehpineda
name: Alejandro H. Pineda
address: Torreón Coauila México
cel: +52 871 186 6100
cv_esp: H.Pineda.Alejandro.esp.pdf
cv_ing: H.Pineda.Alejandro.eng.pdf

# Build settings
markdown: kramdown